package com.quickmaster.config;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.lang.reflect.Constructor;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.function.UnaryOperator;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AppConfigTest
{
    /* --- Desktop resolution --- */

    @Test
    @DisplayName("The default output directory exists on this machine")
    void defaultOutputDirIsAnExistingDirectory()
    {
        assertTrue(Files.isDirectory(Path.of(AppConfig.DEFAULT_OUTPUT_DIR)),
                "not a directory: " + AppConfig.DEFAULT_OUTPUT_DIR);
    }

    @Test
    @DisplayName("Windows: the desktop comes from the user profile")
    void windowsDesktopComesFromTheUserProfile(@TempDir Path tmp) throws Exception
    {
        Path profile = Files.createDirectories(tmp.resolve("profile"));
        Path desktop = Files.createDirectories(profile.resolve("Desktop"));
        Path home = Files.createDirectories(tmp.resolve("home"));          // no Desktop inside
        Files.createDirectories(tmp.resolve("onedrive").resolve("Desktop"));

        String resolved = AppConfig.desktopDir("Windows 11",
                home.toString(),
                env(Map.of("USERPROFILE", profile.toString(),
                           "OneDrive", tmp.resolve("onedrive").toString())));

        assertEquals(desktop.toString(), resolved);
    }

    @Test
    @DisplayName("Windows: a desktop redirected to OneDrive is found")
    void windowsDesktopFallsBackToOneDrive(@TempDir Path tmp) throws Exception
    {
        Path profile = Files.createDirectories(tmp.resolve("profile"));   // no Desktop inside
        Path oneDrive = Files.createDirectories(tmp.resolve("onedrive"));
        Path desktop = Files.createDirectories(oneDrive.resolve("Desktop"));

        String resolved = AppConfig.desktopDir("Windows 11",
                profile.toString(),
                env(Map.of("USERPROFILE", profile.toString(),
                           "OneDrive", oneDrive.toString())));

        assertEquals(desktop.toString(), resolved);
    }

    @Test
    @DisplayName("macOS: the desktop hangs from the home directory")
    void macDesktopComesFromHome(@TempDir Path tmp) throws Exception
    {
        Path home = Files.createDirectories(tmp.resolve("home"));
        Path desktop = Files.createDirectories(home.resolve("Desktop"));

        assertEquals(desktop.toString(),
                AppConfig.desktopDir("Mac OS X", home.toString(), env(Map.of())));
    }

    @Test
    @DisplayName("Linux: a localised desktop is read from user-dirs.dirs")
    void linuxDesktopComesFromXdgUserDirs(@TempDir Path tmp) throws Exception
    {
        Path home = Files.createDirectories(tmp.resolve("home"));
        Path desktop = Files.createDirectories(home.resolve("Escritorio"));
        Path config = Files.createDirectories(home.resolve(".config"));
        Files.writeString(config.resolve("user-dirs.dirs"),
                "# generated by xdg-user-dirs-update\n"
                + "XDG_DOWNLOAD_DIR=\"$HOME/Descargas\"\n"
                + "XDG_DESKTOP_DIR=\"$HOME/Escritorio\"\n");

        assertEquals(desktop.toString(),
                AppConfig.desktopDir("Linux", home.toString(), env(Map.of())));
    }

    @Test
    @DisplayName("Linux: XDG_DESKTOP_DIR wins over the plain ~/Desktop")
    void linuxEnvironmentWinsOverTheConventionalName(@TempDir Path tmp) throws Exception
    {
        Path home = Files.createDirectories(tmp.resolve("home"));
        Files.createDirectories(home.resolve("Desktop"));
        Path shared = Files.createDirectories(tmp.resolve("shared-desktop"));

        assertEquals(shared.toString(),
                AppConfig.desktopDir("Linux", home.toString(),
                        env(Map.of("XDG_DESKTOP_DIR", shared.toString()))));
    }

    @Test
    @DisplayName("Without a desktop folder the home directory is used")
    void desktopFallsBackToHome(@TempDir Path tmp) throws Exception
    {
        Path home = Files.createDirectories(tmp.resolve("headless-home"));

        assertEquals(home.toString(), AppConfig.desktopDir("Linux", home.toString(), env(Map.of())));
        assertEquals(home.toString(), AppConfig.desktopDir("Windows 11", home.toString(), env(Map.of())));
    }

    /* --- Persistence and migration --- */

    @Test
    @DisplayName("A config written before versioning takes the new default output directory")
    void legacyConfigTakesTheNewDefault(@TempDir Path tmp) throws Exception
    {
        Path stored = Files.createDirectories(tmp.resolve("old-export-folder"));
        Path file = tmp.resolve("quickmaster-config.json");
        Files.writeString(file, "{\n  \"outputDir\": " + quoted(stored)
                + ",\n  \"defaultExportFormat\": \"MP3\"\n}");

        AppConfig config = loadFrom(file);

        assertEquals(AppConfig.DEFAULT_OUTPUT_DIR, config.getOutputDir());
        assertEquals("MP3", config.getDefaultExportFormat());
        assertTrue(Files.readString(file).contains("\"configVersion\": " + AppConfig.CONFIG_VERSION),
                "the migrated file must be stamped with the current version");
    }

    @Test
    @DisplayName("An up-to-date config keeps the folder used for the last export")
    void versionedConfigKeepsItsOutputDir(@TempDir Path tmp) throws Exception
    {
        Path stored = Files.createDirectories(tmp.resolve("my-masters"));
        Path file = tmp.resolve("quickmaster-config.json");
        Files.writeString(file, "{\n  \"configVersion\": " + AppConfig.CONFIG_VERSION
                + ",\n  \"outputDir\": " + quoted(stored) + "\n}");

        assertEquals(stored.toString(), loadFrom(file).getOutputDir());
    }

    @Test
    @DisplayName("A stored folder that no longer exists falls back to the default")
    void vanishedOutputDirFallsBackToTheDefault(@TempDir Path tmp) throws Exception
    {
        Path file = tmp.resolve("quickmaster-config.json");
        Files.writeString(file, "{\n  \"configVersion\": " + AppConfig.CONFIG_VERSION
                + ",\n  \"outputDir\": " + quoted(tmp.resolve("unplugged-drive")) + "\n}");

        assertEquals(AppConfig.DEFAULT_OUTPUT_DIR, loadFrom(file).getOutputDir());
    }

    /* --- Helpers --- */

    private static UnaryOperator<String> env(Map<String, String> values)
    {
        Map<String, String> copy = new HashMap<>(values);
        return copy::get;
    }

    /** JSON string literal for a path (Windows separators need escaping). */
    private static String quoted(Path path)
    {
        return "\"" + path.toString().replace("\\", "\\\\") + "\"";
    }

    /** A configuration loaded from {@code file}, independent of the shared instance. */
    private static AppConfig loadFrom(Path file) throws Exception
    {
        Constructor<AppConfig> ctor = AppConfig.class.getDeclaredConstructor();
        ctor.setAccessible(true);
        AppConfig config = ctor.newInstance();
        config.setConfigFilePath(file.toString());
        config.load();
        return config;
    }
}
